### ISSUE TITLE
tested on motorola g84 5g android 14

### ISSUE THREAD

**Issue by Razer-0** [Samw662/android_device_motorola_bangkk-twrp#1]
I have tested this version of twrp on my moto g84, at first glance it allows it to be installed without problems, when starting the operating system it only returns to recovery, it does not allow backups, nor mounting partitions, among others....

**Comment by Samw662** [comment]
Wow
What version of Android were you using? The only image I released it's only for Android 14!!

**Comment by Razer-0** [comment]
> I have tested this version of twrp on my moto g84, at first glance it allows it to be installed without problems, when starting the operating system it only returns to recovery, it does not allow backups, nor mounting partitions, among others....



> Wow What version of Android were you using? The only image I released it's only for Android 14!!

Yes, the version I use is Android 14 build number U1TCS34.22-64-6-1, GOOGLE PLAY SYSTEM UPDATE MAY 1, 2024, ANDROID SECURITY UPDATE APRIL 1, 2024, I will be happy to share all the details you need.

**Comment by Razer-0** [comment]
I also have a problem with the Qualcomm driver for this device. Do you have any idea which one I should install so that the Windows device manager, ports (com and plt) can detect it, if you have information it would be of great help.

**Comment by Samw662** [comment]
dm me in Telegram, you must be doing something wrong.
@Samw662 as well

**Comment by Razer-0** [comment]
> dm me in Telegram, you must be doing something wrong. @Samw662 as well

done

**Comment by Razer-0** [comment]
> dm me in Telegram, you must be doing something wrong. @Samw662 as well

I already wrote to your telegram

**Comment by Samw662** [comment]
wrong process during flashing (flashing recovery as boot)
